version: 2.1

jobs:
  lint:
    docker:
      - image: circleci/node:17.0.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      
      - run:
          name: Check linter
          command: yarn lint

  test:
    docker:
      - image: circleci/node:17.0.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: echo "yarn install"

      - run:
          name: Run tests
          command: echo "EMPTY_TEST"

  deploy:
    docker:
      - image: circleci/node:17.0.1
    environment:
      CI: false # CI as true will consider warning as an error and will stop the deployment
    steps:
      - checkout

      - run:
          name: Configure git
          command: |
            git config --global user.email "mateusfelipefg77@gmail.com"
            git config --global user.name "Mateus Felipe"

      - run:
          name: Install dependencies
          command: yarn install

      - run:
          name: Deploy app
          command: yarn deploy

workflows:
  lint_test_deploy:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - deploy:
          requires:
            - test
